// src/App.tsx
import { useRef, useState } from "react";

import {
	Box,
	Button,
	Heading,
	HStack,
	Icon,
	Spinner,
	Tabs,
	Text,
} from "@chakra-ui/react";

// --icons --
import { LuCloudUpload, LuMedal, LuTable, LuTrophy } from "react-icons/lu";

// -- domain --
import { uploadData } from "./services/general";
import GeneralTable from "./components/GeneralTable";
import CompetitorTable from "./components/CompetitorTable";
import TrophyTable from "./components/TrophyTable";
import InstructorTable from "./components/InstructorTable";

export default function App() {
	const inputRef = useRef<HTMLInputElement>(null);
	const [loading, setLoading] = useState(false);
	const [reloadKey, setReloadKey] = useState(0);

	const handleUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
		try {
			const file = event.target.files?.[0];
			if (!file) return;

			if (!file.name.toLowerCase().endsWith(".csv")) {
				alert("Sólo se permiten archivos CSV");
				return;
			}

			setLoading(true);
			await uploadData(file);
			alert("Datos cargados correctamente");

			setReloadKey((prev) => prev + 1);
		} catch (error) {
			console.error(error);

			alert("Error en la carga del archivo");
		} finally {
			setLoading(false);

			if (inputRef.current) {
				inputRef.current.value = "";
			}
		}
	};

	return (
		<Box minH="100vh">
			<Box p="6">
				<HStack justify="space-between" wrap="wrap">
					<Text fontSize="2xl" fontWeight="bold">
						Copa Koguryo
					</Text>

					<Button variant="surface" onClick={() => inputRef.current?.click()}>
						{loading ? (
							<Spinner size="sm" />
						) : (
							<>
								<Icon as={LuCloudUpload} />
								Cargar CSV
							</>
						)}
					</Button>

					<input
						ref={inputRef}
						type="file"
						hidden
						accept=".csv"
						onChange={handleUpload}
					/>
				</HStack>
			</Box>

			<Box p="6">
				<Tabs.Root defaultValue="data" variant="subtle" fitted>
					<Tabs.List borderWidth="1px" mb="4">
						<Tabs.Trigger value="data">
							<Icon as={LuTable} />
							Datos
						</Tabs.Trigger>

						<Tabs.Trigger value="trophies">
							<Icon as={LuTrophy} />
							Medallas
						</Tabs.Trigger>

						<Tabs.Trigger value="ranking">
							<Icon as={LuMedal} />
							Ranking
						</Tabs.Trigger>

						<Tabs.Indicator rounded="lg" />
					</Tabs.List>

					<Tabs.Content value="data">
						<GeneralTable reloadKey={reloadKey} />
					</Tabs.Content>

					<Tabs.Content value="trophies">
						<TrophyTable reloadKey={reloadKey} />
					</Tabs.Content>

					<Tabs.Content value="ranking">
						<HStack justify="space-between" align="center">
							<Box>
								<Heading size="2xl" textAlign="center" mb="5">
									Instructores
								</Heading>
								<InstructorTable reloadKey={reloadKey} />
							</Box>

							<Box>
								<Heading size="2xl" textAlign="center" mb="5">
									Top 10 Danes
								</Heading>
								<CompetitorTable category="dan" reloadKey={reloadKey} />
							</Box>

							<Box>
								<Heading size="2xl" textAlign="center" mb="5">
									Top 10 Colores
								</Heading>
								<CompetitorTable category="color" reloadKey={reloadKey} />
							</Box>
						</HStack>
					</Tabs.Content>
				</Tabs.Root>
			</Box>
		</Box>
	);
}

// src/app/app.component.ts
import { Component, inject } from '@angular/core';
import { MaterialModule } from './material.module';
import { MatSnackBar } from '@angular/material/snack-bar';
// components
import { GeneralComponent } from './components/general/general.component';
import { InstructorsComponent } from './components/instructors/instructors.component';
import { CompetitorComponent } from './components/competitor/competitor.component';
import { TrophiesComponent } from './components/trophies/trophies.component';
// services
import { GeneralService } from './services/general.service';
import { SharedService } from './services/shared.service';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    MaterialModule,
    GeneralComponent,
    InstructorsComponent,
    CompetitorComponent,
    TrophiesComponent,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  selectedFile: File | null = null;
  isLoading = false;

  private _snackBar = inject(MatSnackBar);

  constructor(
    private generalService: GeneralService,
    private sharedService: SharedService
  ) {}

  onFileSelected(event: Event) {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      const file = input.files[0];

      if (!file.name.toLowerCase().endsWith('.csv')) {
        this._snackBar.open('Sólo se permiten archivos CSV.', 'Cerrar', {
          duration: 3000,
        });
        input.value = ''; 
        return;
      }

      this.isLoading = true;

      this.generalService.uploadData(file).subscribe({
        next: () => {
          this._snackBar.open('Datos cargados correctamente', 'Cerrar', {
            duration: 3000,
          });
          this.sharedService.upload();
        },
        error: (error) => {
          console.error('Error en la carga: ', error);
          this._snackBar.open('Error en la carga del archivo', 'Cerrar', {
            duration: 3000,
          });
        },
        complete: () => {
          this.isLoading = false;
          input.value = '';
        },
      });
    }
  }
}

<header>
  <div class="logo">
    <h1>Copa Koguryo</h1>
    <img src="/assets/logo.png" alt="Logo" />
  </div>

  <mat-button-toggle-group>
    <button mat-flat-button (click)="fileInput.click()" color="primary">
      @if (!isLoading) {
      <ng-container>
        <div class="icon-text">
          <mat-icon>cloud_upload</mat-icon>
          <p>Cargar</p>
        </div>
      </ng-container>
      } @else {
      <ng-container>
        <mat-spinner diameter="20"></mat-spinner>
      </ng-container>
      }
    </button>
    <input #fileInput type="file" hidden (change)="onFileSelected($event)" />
  </mat-button-toggle-group>
</header>

<mat-tab-group>
  <mat-tab>
    <ng-template mat-tab-label>
      <span class="icon-header">
        <mat-icon>leaderboard</mat-icon>
        Ranking
      </span>
    </ng-template>
    <div class="ranking-container">
      <div class="table-container">
        <h3>Instructores</h3>
        <app-instructors></app-instructors>
      </div>

      <div class="table-container">
        <h3>Top 10 Danes</h3>
        <app-competitor [category]="'dan'"></app-competitor>
      </div>

      <div class="table-container">
        <h3>Top 10 Colores</h3>
        <app-competitor [category]="'color'"></app-competitor>
      </div>
    </div>
  </mat-tab>

  <mat-tab>
    <ng-template mat-tab-label>
      <span class="icon-header">
        <mat-icon>emoji_events</mat-icon>
        Medallas
      </span>
    </ng-template>
    <app-trophies></app-trophies>
  </mat-tab>

  <mat-tab>
    <ng-template mat-tab-label>
      <span class="icon-header">
        <mat-icon>table_chart</mat-icon>
        Datos
      </span>
    </ng-template>
    <app-general></app-general>
  </mat-tab>
</mat-tab-group>
